### ISSUE TITLE
Runkeeper authorization failure?

### ISSUE THREAD

**Issue by loedeman** [seripap/GPX-to-Runkeeper#1]
I am trying to import GPX files into my Runkeeper account. I created an application. However, when running the script, I get an 500 Internal Server Error on the POST to https://runkeeper.com/apps/authorize?allow= :( . Do you perhaps have any idea of what is going wrong? Thanks!

**Comment by seripap** [comment]
Hey, it's been a few years since i've touched this, but it could be your redirect_url.

Try running it encapsulated in its own root.

@index.dist.php

```
$redirect_url = 'http://localhost:8080/index.dist.php';
```

Then start a localized php instance to that folder

```
php -S localhost:8080
```

**Comment by loedeman** [comment]
Hey, thanks for your help! I just tried doing what you suggested. The problem seems to be the redirect URI never gets called, there is a server error before the redirect URI should be called. I will try creating a ticket with Runkeeper to find out more ;) . It would be nice to have a possibility to import all my activities automatically ;) .

**Comment by seripap** [comment]
Great- hopefully they can resolve it for you. I don't think their API has been updated in years either, so let me know if you find out anything!
